### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Enmaboya** [epartment/nova-dependency-container#10]
Hi
there is a question about belongsto.
did not quite understand how dependsOnNotEmpty works.

Suppose I have a cafe, a cafe has a city.
Can I use this package to add editable city fields ('title' and others) to the cafe's resource?

**Comment by unxsist** [comment]
`dependsOnNotEmpty` makes fields required when the dependency is NOT empty. It does not allow you to add fields to a related resource.
