### ISSUE TITLE
Issue when used with Ebess\AdvancedNovaMediaLibrary

### ISSUE THREAD

**Issue by jmaloneytrevetts** [epartment/nova-dependency-container#108]
I have image fields from Ebess\AdvancedNovaMediaLibrary showing/hiding correctly but if they will not save at all.  When moved outside of the NovaDependencyContainer, they save correctly

**Comment by jmaloneytrevetts** [comment]
I did not have the trait set.  My fault.

**Comment by muhghazaliakbar** [comment]
@jmaloneytrevetts What do you mean the `set the Trait`?

**Comment by wize-wiz** [comment]
@muhghazaliakbar 

Add the `Epartment\NovaDependencyContainer\HasDependencies` trait to your Nova Resource as described in the readme.
