### ISSUE TITLE
Image Field Type

### ISSUE THREAD

**Issue by garrettbland** [epartment/nova-dependency-container#11]
I am trying to use the default 'Image' field type with this package but it always just defaults the value in the database. I can get the image to upload to my s3 bucket, but somewhere it seems to remove the path value. Other fields all work flawlessly. Is there something obvious I'm doing wrong or this a bug?

`NovaDependencyContainer::make([
                 Image::make('Ad Image','ad_image')
                 ->disk('s3')
                 ->path('ads/'.$currentYear.'/'.$currentMonth.'/banner')
                 ->hideFromIndex()
                 ->prunable(),
            ])->dependsOn('type', 0),`

**Comment by gwleuverink** [comment]
I am experiencing the same issue.

**Comment by webappbuilder** [comment]
Me too. Laravel Nova 1.2.0.

**Comment by Mesj96** [comment]
#me2 XD
I hope you guys will fix this problem soon :)

**Comment by wize-wiz** [comment]
@garrettbland @Mesj96 @webappbuilder @gwleuverink Does this only occur with cloud storage? I'm unable to reproduce this using local storage.

**Comment by wize-wiz** [comment]
If this issue occurs and someone can give a clear example, please open a new issue.
