### ISSUE TITLE
does not work with : fieldsForCreate, fieldsForUpdate

### ISSUE THREAD

**Issue by issour** [epartment/nova-dependency-container#117]
Hi,
As Documentation says :

Dynamic Field Methods Precedence ::
The fieldsForIndex, fieldsForDetail, fieldsForCreate, and fieldsForUpdate methods always take precedence over the fields method.

in trait HasDependencies

the collection is for fields : `$fields = $this->filter($this->fields($request));`

Many Thx !!!

**Comment by ragingdave** [comment]
Would you be able to expand a bit on what does not work? Perhaps a bit of a clearer example along with expected vs actual behavior?

**Comment by lstoyanoff** [comment]
https://nova.laravel.com/docs/3.0/resources/fields.html#dynamic-field-methods

HasDependencies trait overrides the `availableFields` method which is used to determine if there are specific fields set for the different pages (Index, Details, Create, Update).

https://github.com/epartment/nova-dependency-container/blob/master/src/HasDependencies.php#L21-L47

Maybe it is a better idea to first get the `fieldsMethod` and then get the appropriate fields.

```
    /**
     * @param NovaRequest $request
     * @return FieldCollection|\Illuminate\Support\Collection
     */
    public function availableFields(NovaRequest $request)
    {
        $method = $this->fieldsMethod($request);
        // needs to be filtered once to resolve Panels
        $fields = $this->filter($this->{$method}($request));
        ...
    }
```

**Comment by jp-gauthier** [comment]
Solved by this pull request : #170

**Comment by leadbox-ryan** [comment]
I think i found the source of my new bug. 

Call to undefined method App\Nova\___::fieldsMethod()

**Comment by BinaryKitten** [comment]
> I think i found the source of my new bug.
> 
> Call to undefined method App\Nova___::fieldsMethod()

Please make sure you're running up to date nova.
or refer to readme for version limitation
> Versions
>
> -  install v1.2.x for Laravel v5.8 or v6.x and Nova 2.x
> -  install v1.1.2 for Laravel v5.7 and Nova v1.x

**Comment by leadbox-ryan** [comment]
Thanks. I'm on Nova ^2.0 so that's what it was.

I'm really appreciative I found this post with the version. I switched this from ^1.2 to a hard 1.3.2 and it works fine — and will probably work fine until I finish the update process to L8 N3.
