### ISSUE TITLE
Package ABANDONED

### ISSUE THREAD

**Issue by izi-dev** [epartment/nova-dependency-container#119]

**Comment by ragingdave** [comment]
@wize-wiz I would be very sad to see that this is getting abandoned, but after about 6 months without a peep, I can't really argue that it's not abandoned.

**Comment by wize-wiz** [comment]
@ragingdave Yea some serious happened. If you like, accept the invite and I'll catch up somewhere end of the week. If you know anybody else seriously enough to maintain, I'll change your permissions to invite as well.
