### ISSUE TITLE
Invalid argument supplied for foreach error with checkbox

### ISSUE THREAD

**Issue by RicLeP** [epartment/nova-dependency-container#12]
When using this package on a boolean I get the following error:

Invalid argument supplied for foreach() {"userId":1,"email":"xxxxxx","exception":"[object] (ErrorException(code: 0): Invalid argument supplied for foreach() at \vendor\epartment\

nova-dependency-container\src\NovaDependencyContainer.php:92

My resource is:

	Boolean::make('Other qualification', 'qualification_other')
		->hideFromIndex()
		->help('Please specify'),

	NovaDependencyContainer::make('Dependent settings', [
		Text::make('Qualification', 'qualification_other_name')
	])->dependsOnNotEmpty('qualification_other')->onlyOnForms(),

**Comment by unxsist** [comment]
To use checkboxes, you should specify the toggle value. See #1.
