### ISSUE TITLE
dependsOnNot - Not working for integer values

### ISSUE THREAD

**Issue by BenWalters** [epartment/nova-dependency-container#121]
When using the newly implemented `->dependsOnNot('field', 'value')` if value is an integer then the condition is never met. 

 `->dependsOnNot('field', 2)` - Not working
 `->dependsOnNot('field', 0)` - Not working
 `->dependsOnNot('field', '0')` - Works

This behaviour is different to `->dependsOn('field', 'value')` which does support integer comparison.

 `->dependsOn('field', 2)` - Works
 `->dependsOn('field', 0)` - Works
 `->dependsOn('field', '0')` - Works

**Comment by wize-wiz** [comment]
@BenWalters Could you create PR? If not, this has to go on the list of many other things ..

**Comment by BenWalters** [comment]
@wize-wiz  it's not something I can do at the moment but when we revisit this area of our application I'll see about fixing/PR'ing this (if it's not already been done).
