### ISSUE TITLE
Question about dependsOn 'AND' #question

### ISSUE THREAD

**Issue by Jun-ocx** [epartment/nova-dependency-container#129]
Simply I want to show the dependent field when there are multiple fields with values are matched the condition

Want to make Text field appeared when active 1 and active 2 toggles are switched on coincidently

Anyone knows how to implement this?

```
Toggle::make('Active1', 'active_one)
Toggle::make('Active2', 'active_two)

NovaDependencyContainer::make([
     Text::make('I want AND', 'text')
])->dependsOn('active_one', 1 && 'active_two', 2)
```

Thank you

**Comment by Meteorstrikes** [comment]
Same. I need this ability, too.

**Comment by ragingdave** [comment]
I believe from a past issue, chaining dependsOn result in AND, so the code here would read:

```
Toggle::make('Active1', 'active_one)
Toggle::make('Active2', 'active_two)

NovaDependencyContainer::make([
     Text::make('I want AND', 'text')
])->dependsOn('active_one', 1)
->dependsOn('active_two', 2)
```

**Comment by emjayess** [comment]
> I believe from a past issue, chaining dependsOn result in AND, [...]

I expected 'AND' behavior from chaining together two or more (`->dependsOn($f1, $v1)/*AND*/->dependsOn($f2, $v2)`), however the behavior I am observing when I attempt this is evidently OR behavior. 😕

It might be appreciated to adopt the conventions of Eloquent / Laravel's DB query builder method chaining, in which `->where()->where()` implies AND and `->where()->orWhere()` is explicitly OR.

**Comment by ragingdave** [comment]
127 explains the issue better for this, closing this issue.
