### ISSUE TITLE
Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by crumb1e** [epartment/nova-dependency-container#13]
I'm getting the foreach error when using a checkbox even after double checking against the other checkbox issues on here.

            Boolean::make('Featured', 'featured'),
            NovaDependencyContainer::make('Dependent settings', [
                Number::make('Featured Priority', 'featured_priority')
            ])->dependsOn('featured', true)->onlyOnForms(),

**Comment by laurencei** [comment]
I have same issue for a select box...

**Comment by bcoelhonqda** [comment]
Me too

**Comment by noahlocke** [comment]
same here:

```php

            Number::make('Other','other_hours')->help('(non-billable)'),
            
            NovaDependencyContainer::make('Dependent settings', [
                TextArea::make('Other Description','other_hours_description')
            ])->dependsOn('other_hours', 0)->hideFromIndex(),
```

**Comment by unxsist** [comment]
Hi,

You should not add a title to the Dependency Container as that's not valid. Correct syntax should be:

```php
Number::make('Other','other_hours')->help('(non-billable)'),

NovaDependencyContainer::make([
    TextArea::make('Other Description','other_hours_description')
])->dependsOn('other_hours', 0)->hideFromIndex(),
```
