### ISSUE TITLE
Feature: don't clean fields values between depends fields changes

### ISSUE THREAD

**Issue by 4n70w4** [epartment/nova-dependency-container#144]
Hi! I would like to be able not to clear, but to store the values of the fields in the NovaDependencyContainer while the values in dependsOn are changed.

Currently, when dependsOn changes and returns it back, the fields are reset value to default.

**Comment by ragingdave** [comment]
Feel free to submit a PR to enable the functionality and we can take a look but that's not something I'm looking to tackle at the moment directly.
