### ISSUE TITLE
Conflicts with redeclared ActionRequest

### ISSUE THREAD

**Issue by 4n70w4** [epartment/nova-dependency-container#145]
Hi! I redeclare `ActionRequest` in my app, but this package also redeclare `ActionRequest` and brokes all my app.

It will be very great if you don't do it inside this package, but let the user do it in application.

**Comment by ragingdave** [comment]
Unfortunately, this package seems to be heavily tied to overriding that ActionRequest. If you have a way around that, I'd be all ears as I'm not a huge fan of that either, but as of now it's going to have to stay this way without a pretty massive rework.
