### ISSUE TITLE
Nova Images not downloading from s3

### ISSUE THREAD

**Issue by gustav1105** [epartment/nova-dependency-container#148]
The dependency container is causing files that are uploaded to s3, to not be downloadable, when using s3 storage to upload files, it can upload successfully but when trying to download said file, the server responds with failed no file.

Not sure how to fix this or if there is a open issue for it, or a possible workaround

**Comment by ragingdave** [comment]
Can you elaborate on specifically how it's the dependency container that is specifically causing this as well as maybe some field setups to be able to replicate? I actually use s3 for images so I can certainly test this, just wondering if the container is the culprit

**Comment by gustav1105** [comment]
Good morning It has been implemented using s3 see below snippet

I have this in my fields array of my nova resource

//TODO: Nova dependency container is failing cannot download video or audio assets cms
NovaDependencyContainer::make([
    //TODO: advanced image implementation is failing due to dependency container wrapping
    Image::make('Image')
        ->disk('s3')
        ->preview(function ($value) {
            return $value;
        })
        ->disableDownload()
        ->hideFromIndex()
])->dependsOn('media_type', KnowledgeCardType::IMAGE),
What I can see is that if I remove the disable download button. I have can click download but It fails to find the file. 

Hope it helps. Let me know if you require more info

**Comment by ragingdave** [comment]
It looks as though how you are looking to generate a preview isn't correct and you would need to generate the url directly.
https://nova.laravel.com/docs/3.0/resources/file-fields.html#customizing-previews

Closing as this doesn't appear to be an issue with the dependency container, but in the usage of the Image field.
Feel free to reply back if there is still an issue.
