### ISSUE TITLE
validateFields() is not compatible after updating to Nova 3.21.0

### ISSUE THREAD

**Issue by kevindb** [epartment/nova-dependency-container#149]
ErrorException: Declaration of Epartment\NovaDependencyContainer\HasDependencies::validateFields() should be compatible with Laravel\Nova\Actions\Action::validateFields(Laravel\Nova\Http\Requests\ActionRequest $request).

Using Laravel Nova 3.21.0 and Nova Field Dependency Container 1.2.11. Confirmed that this error does not occur with Nova 3.20.0.

It looks like Nova's `validateFields()` now takes an argument `$request` that NovaDependencyContainer's `validateFields()` is not accepting.
Stack trace is attached. Please let me know if there is anything else I can do to help diagnose.

![Screen Shot 2021-02-02 at 4 45 39 PM](https://user-images.githubusercontent.com/3468013/106667682-3a62d000-6577-11eb-99af-222e118d348b.jpg)

**Comment by gmedeiros** [comment]
I am too facing this problem. I'll try to send a quick hotfix in a few minutes.

**Comment by gmedeiros** [comment]
Please check PR #150 
@kevindb In the meantime, you can use our branch. It is a just a quick fix, haven't tested it at all yet.

**Comment by gmedeiros** [comment]
> Please check PR #150
> @kevindb In the meantime, you can use our branch. It is a just a quick fix, haven't tested it at all yet.

Actually, I closed the PR since it does not completely solve the issue.
