### ISSUE TITLE
[Question] Future of nova-dependency-container

### ISSUE THREAD

**Issue by Naoray** [epartment/nova-dependency-container#153]
Based on the unanswered issues, open PRs and the lack of progress (last commit in June 2020), I'd like to know if this project will be abandoned? And if not... is there an existing plan on when we can expect some progress?

I am currently utilizing this package in a client project and want to know if I have to plan some time ahead to maintain my version of the package or if I can expect some progress from the owners.

Thanks in advance :pray:

**Comment by ragingdave** [comment]
Although I'm not the owner specifically, I would be willing to try and work through some of the issues/PRs. I do have a full time job which takes up a large amount of my time though so it won't be overnight change. I would like to see @wize-wiz come back into this as well as I'm not really in a place to take over a package completely. I have turned on my notifications though for all activity here so I can be more aware of what's going on.

**Comment by ragingdave** [comment]
Also to all contributors that might see this, I'll work on updating the readme (or maybe someone can do it for me), but I think for safety sake, please do not commit any dist js/csss. This poses a security risk as no one is actually going to be reading through the dist versions to confirm it's what it should be. It's also one less step for you as a pull requester, as you don't have to add dist assets.

**Comment by wize-wiz** [comment]
@ragingdave Yes, I was planning on a comeback for all the packages I've made on github, including maintaining this package. 3 weeks ago, I've quit all my current projects that has been eating up all my time since the last 2 years. I'm still in the middle of organizing everything that has been going on with the lock-down here in Germany, but I should be able to reliably plan some time for this package.

**Comment by midorikocak** [comment]
following

**Comment by cord** [comment]
following

**Comment by cord** [comment]
https://github.com/epartment/nova-dependency-container/issues/188 is a showstopper
