### ISSUE TITLE
Can you please release new version

### ISSUE THREAD

**Issue by BobbyBorisov** [epartment/nova-dependency-container#155]
Hey guys! First of all thank you for the amazing work you are doing for the Nova community!

Currently we have an issue with latest version 1.2.11 regarding ability to show helper texts. I saw it is fixed by [6d3cafee2165c34986a24925784da46216597eea](https://github.com/epartment/nova-dependency-container/commit/6d3cafee2165c34986a24925784da46216597eea) in `master`

Could you please release a new version? Thank you in advance

**Comment by ragingdave** [comment]
new 1.2.12 is released
