### ISSUE TITLE
Problem with displayUsingLabels()

### ISSUE THREAD

**Issue by fukumori** [epartment/nova-dependency-container#16]
When i do:
```php
...
            NovaDependencyContainer::make([
                Select::make('Select', 'select')
                    ->options([
                        'yes' => 'Yes, please',
                        'no' => 'Not',
                    ])
                    ->displayUsingLabels(),
            ])->dependsOn('some_field', 'some_value'),
        ];
```
On details of resource select attribute show the key, not label.

**Comment by JILeXanDR** [comment]
The same is when using **displayUsing()**. Callback is never called :(

**Comment by daguilarm** [comment]
Same here!

**Comment by rk** [comment]
Looks like the issue isn't related to the Vue component, based upon my tinkering. It might be related to the PHP Field though. I think that's because it's actually descended from a Field instead of a Panel. But I can't be 100% sure yet, as I'm pretty new to Nova.

**Comment by wize-wiz** [comment]
#68

**Comment by wize-wiz** [comment]
Fixed in https://github.com/epartment/nova-dependency-container/commit/dddd8a470d57d0885d6ec2531e6c7cc801d45b58
