### ISSUE TITLE
`dependsOnNotEmpty` doesn't work

### ISSUE THREAD

**Issue by nikans** [epartment/nova-dependency-container#161]
```php

BelongsTo::make('Type', 'exerciseType', 'App\Nova\ExerciseType')
    ->rules('required'),

NovaDependencyContainer::make([
    BelongsTo::make('Question', 'exerciseQuestion', 'App\Nova\ExerciseQuestion')
])->dependsOnNotEmpty('exerciseType'),

```

**Comment by ragingdave** [comment]
It looks like you aren't using this correctly. See the docs here: https://github.com/epartment/nova-dependency-container#belongsto-dependency

**Comment by nikans** [comment]
@ragingdave I literally use it just as stated in the docs. `dependsOn` works, `dependsOnEmpty` works, `dependsOnNotEmpty` doesn't work.

**Comment by dkulyk** [comment]
This is a bug. 
```
 protected function getFieldLayout($field, $value = null)
    {
        if (count( ($field = explode('.', $field)) ) === 1) {
            // backwards compatibility, property becomes field
            $field[1] = $field[0];
        }
        return [
            // literal form input name
            'field' => $field[0],
            // property to compare
            'property' => $field[1],
            // value to compare
            'value' => $value,
        ];
    }
```

getFieldLayout always adds `value`. 

```if (dependency.hasOwnProperty('notEmpty') && dependencyValue) ```  not passed and next 
```if (dependency.hasOwnProperty('value') && dependencyValue == dependency.value)``` passed because both values is null.

no need to add value if dependency do not use it? Or need update checking like
```
if() {}
else if()
else if()
...
```
I used this for notEmpty:
```
                ->withMeta([
                    'dependencies' => [
                        ['field' => 'generalPlan', 'property' => 'generalPlan', 'notEmpty' => true],
                    ],
                ]),
```
This works well.

**Comment by nikans** [comment]
@dkulyk Thanks.
