### ISSUE TITLE
Support for BooleanGroup

### ISSUE THREAD

**Issue by NoahNxT** [epartment/nova-dependency-container#164]
I've tried to work with a Boolean Group because it works kinda the same way as a select. But for some reason I can't get it working. What could be the issue? Or is boolean group not supported?

```
           BooleanGroup::make('Permissions', 'permissions')->options(
                [
                    'create' => 'Create',
                    'read' => 'Read',
                    'update' => 'Update',
                    'delete' => 'Delete',
                ]
            ),

            NovaDependencyContainer::make(
                [
                    Text::make('Name', 'first_name')
                ]
            )->dependsOn('permissions', 'create'),
```

**Comment by ragingdave** [comment]
This is currently unsupported (but would welcome a PR to support it), as from your example, you are missing a key point of what the value of the BooleanGroup option should be if it were to work.
IE.
```
dependsOn('permissions.create', true);
// OR
dependsOn('permissions.create', false);
```
I'm not saying this example works, only that it would be the "correct" way it would if it did for PR guidance purposes.

**Comment by NoahNxT** [comment]
unfortunately my coding skills are not advanced enough to search trough your code, also I'm sitting with the question if there is a support for the **_OptimistDigital\MultiselectField\Multiselect_** package.

**Comment by Sohail-purelogics** [comment]
Any solution here?
