### ISSUE TITLE
BUG: Compatibility with fieldsForIndex, fieldsForDetail functions on Nova 3.X

### ISSUE THREAD

**Issue by albertgpdev** [epartment/nova-dependency-container#169]
Hi I am experiencing some issues with the Nova 3.X fieldsForIndex, fieldsForDetail functions and looking in the code, I have found that the problem is due to this function where I think these two lines are missing to be compatible with those functions

```
$method = $this->fieldsMethod($request);
$fields = $this->filter($this->filter($this->{$method}($request)));
```

The function should look like this:
```

public function availableFields(NovaRequest $request)
    {
        $method = $this->fieldsMethod($request);

        // needs to be filtered once to resolve Panels
        $fields = $this->filter($this->filter($this->{$method}($request)));
        $availableFields = [];

        foreach ($fields as $field) {
            if ($field instanceof NovaDependencyContainer) {
                $availableFields[] = $this->filterFieldForRequest($field, $request);
                if ($field->areDependenciesSatisfied($request) || $this->extractableRequest($request, $this->model())) {
                    if ($this->doesRouteRequireChildFields()) {
                        $this->extractChildFields($field->meta['fields']);
                    }
                }
            } else {
                $availableFields[] = $this->filterFieldForRequest($field, $request);
            }
        }

        if ($this->childFieldsArr) {
            $availableFields = array_merge($availableFields, $this->childFieldsArr);
        }

        $availableFields = new FieldCollection(array_values($this->filter($availableFields)));

        return $availableFields;
    }
```

Best,

**Comment by jp-gauthier** [comment]
Solved by this pull request : #170

**Comment by ragingdave** [comment]
merged #170

**Comment by BinaryKitten** [comment]
Hi Team,

Is there any chance that this can be pushed to a release? - i see the bug fix has been merged to master, but no subsequent release or tag made so packagist hasn't updated.

Would be appreciative if we could?
Thanks

**Comment by ragingdave** [comment]
Tagged v1.3.3!

**Comment by stefblokdijk** [comment]
I noticed that this #170 resulted in the following error
```
Call to undefined method App\Nova\Campaign::fieldsMethod()
```

I recently upgrade from 1.3.2 to 1.3.3. I'm using Nova version 2.12.2

**Comment by BinaryKitten** [comment]
> I noticed that PR #170 resulted in the following error
> 
> ```
> Call to undefined method App\Nova\Campaign::fieldsMethod()
> ```
> 
> I recently upgrade from 1.3.2 to 1.3.3. I'm using Nova version 2.12.2 and Laravel 5.8.38 on this project.

yeah this was a deliberate patch for Nova 3 -
not sure on what @ragingdave thinks, but you can limit your inclusion of this in your composer.json to 1.3.2 it will prevent the error.
