### ISSUE TITLE
It's not showing field

### ISSUE THREAD

**Issue by stonkeep** [epartment/nova-dependency-container#17]
It's not showing NovaDependencyContainer field when data is pre loaded 
Exemple
This is when screen is loading at first time
<img width="991" alt="screen shot 2018-09-30 at 16 45 13" src="https://user-images.githubusercontent.com/3990028/46261894-4bdfcd00-c4d0-11e8-9193-313df37522a1.png">

And this is after change 'Tipo' field
<img width="928" alt="screen shot 2018-09-30 at 16 48 01" src="https://user-images.githubusercontent.com/3990028/46261910-a2e5a200-c4d0-11e8-88fe-089e23620ebd.png">

**Comment by satoved** [comment]
Can confirm, tried to trace the bug, bug the vue watcher has {immediate: true}. Don't know.
