### ISSUE TITLE
When using route:cache the action route is not overriden

### ISSUE THREAD

**Issue by sash** [epartment/nova-dependency-container#172]
/nova-api/{resource}/action is overriden in FieldServiceProvider
```php
        Event::listen(NovaServiceProviderRegistered::class, function () {
            app('router')->middleware('nova')->post('/nova-api/{resource}/action', 
                ['uses' => '\Epartment\NovaDependencyContainer\Http\Controllers\ActionController@store']);
        });
```

That does not have any effect when you use `./artisan route:cache`, that route is not overridden, and therefore the unrequited dependencies are not removed from the validation!

Please advice!

**Comment by ragingdave** [comment]
Great catch on this, I've got a fix that should address it committed onto master. If you don't mind just giving it a shot to confirm the fix, we can tag a new release.
https://github.com/epartment/nova-dependency-container/commit/58e75c710e5312b6e3e319132e4b4ff434822c5e

**Comment by sash** [comment]
Thanks. I'll give it a try tomorrow and I'll let you know

**Comment by sash** [comment]
I checked and this solution indeed fixes it! Thanks! Looking forward to your next release!
