### ISSUE TITLE
Doesn't handle Toggle custom field

### ISSUE THREAD

**Issue by szsori** [epartment/nova-dependency-container#2]
This currently doesn't work with the Toggle custom field type:
https://novapackages.com/packages/davidpiesse/nova-toggle

It does correctly hide the dependent option, but changing the toggle does nothing.  The code works perfectly if modified to Boolean instead.

Sample:
```
Toggle::make('Our Option', 'selectable_option')->hideFromIndex(),
NovaDependencyContainer::make('Dependent settings', [
   Trix::make('Details', 'selectable_option_details'),
])->dependsOn('selectable_option', 1)->onlyOnForms(),
```

**Comment by unxsist** [comment]
Hi @szsori 

I've just pushed the 1.0.1 release which adds better support for 3rd party Nova fields. Using the `dependsOnCustomComponent` method on the field, you can add listeners for 3rd party components. I've updated the README to reflect those changes and took your nova-toggle component as an example.

You can now use those fields and the field dependencies will work like expected
