### ISSUE TITLE
Belongsto field not getting populated

### ISSUE THREAD

**Issue by lvdhoorn** [epartment/nova-dependency-container#21]
Thanks for this awesome package for Nova!
I found a bug when trying to use a belongsto field inside the Nova Dependency Container. It is not getting populated. Instead you get an error like "trying to get property of non-object". Field works fine outside the container.

**Comment by liefie** [comment]
I see the same bug, perhaps something has changed in Nova?

I have the trait, but all my BelongsTo show up empty and trigger the error as above.

**Comment by edgarnadal** [comment]
Tried with HasDependencies trait and it worked good. Thanks! @satoved

**Comment by mterchila** [comment]
Same issue here.

**Comment by mterchila** [comment]
I figured out what was causing my issue - may help with troubleshooting this down the road. I was using the `merge()` method to add the dependency-container field to my resource, see the following link for more info:

https://nova.laravel.com/docs/1.0/resources/fields.html#place-field

Once I stopped using it and placed it in the original fields array on my resource the belongsto field populated values correctly again.

**Comment by wize-wiz** [comment]
Using `HasDependency` indeed solves the problem, I will update the README about this.
