### ISSUE TITLE
Boolean Field Submitting true value as "true"

### ISSUE THREAD

**Issue by gcornhill** [epartment/nova-dependency-container#24]
On submit of the form, if there is a boolean checkbox inside a dependency container, the value is getting passed as string "true" instead of true. Help!

**Comment by unxsist** [comment]
This is fixed in master, a new version will be available soon.

**Comment by ferrl** [comment]
Hello, @unxsist. Any idea when you will tag a new release?

I've run into this bug and took a very long time until I was able to track it to this issue. Just updated the dependency in my project to `dev-master` and it's working fine.
