### ISSUE TITLE
Trait Not Found

### ISSUE THREAD

**Issue by devotoare** [epartment/nova-dependency-container#26]
Followed directions and am getting an error. Likely me doing something wrong. Please help?

```
namespace App\Nova;

use Laravel\Nova\Fields\ID;
use Laravel\Nova\Fields\Number;
use Laravel\Nova\Fields\Select;
use Illuminate\Http\Request;
use Laravel\Nova\Http\Requests\NovaRequest;
use Eparment\NovaDependencyContainer\HasDependencies;

class Customer extends Resource
{
    use HasDependencies;
```

![screenshot-2018 10 23-19-40-52](https://user-images.githubusercontent.com/5583396/47402735-9c2b0300-d6fb-11e8-8b34-498649b63654.png)

**Comment by azurinspire** [comment]
There is type in documentation:
`use Eparment\NovaDependencyContainer\HasDependencies;`
should be
`use Epartment\NovaDependencyContainer\HasDependencies;`

**Comment by devotoare** [comment]
@azurinspire thanks so much!

This is a typo in the readme. 

Now I get a new error:
`Class 'App\Nova\NovaDependencyContainer' not found` 

![screenshot-2018 10 24-00-45-12](https://user-images.githubusercontent.com/5583396/47414553-15d7e680-d726-11e8-8190-3a6936f8d589.png)

Any ideas?

**Comment by azurinspire** [comment]
You are missing the other ’use’ which is correctly in documentation

**Comment by devotoare** [comment]
@azurinspire derp. yes. yes it is. thank you!
