### ISSUE TITLE
File Field Type

### ISSUE THREAD

**Issue by anakadote** [epartment/nova-dependency-container#28]
I am unable to use this package with the "File" field type, as the file is never uploaded to the server:

    Select::make('Type')->options([
        'article' => 'Article',
        'file'    => 'File',
    ])->sortable()->displayUsingLabels(),

    NovaDependencyContainer::make([
        File::make('File')
            ->disk('local')
    ])->dependsOn('type', 'file'),

Furthermore, when using validation it's clear that the field's data is not being sent to the server, as validation fails and returns, "The file field is required.":

    NovaDependencyContainer::make([
        File::make('File')
            ->disk('local')
            ->rules('required', 'file')
    ])->dependsOn('type', 'file'),

**Comment by niladam** [comment]
Apparently this is happening with all the upload fields. I'm encountering the same issue.

**Comment by julianfox** [comment]
Same problem here

**Comment by 949mac** [comment]
I'm having this issue too

**Comment by garyonyx** [comment]
Having this issue as well.

**Comment by niladam** [comment]
I'm gonna go ahead and think this has been abandoned. Too bad, i really saw good use and the work was pretty solid.

I'm sorry to see it fade.

**Comment by garyonyx** [comment]
@niladam have you found another working package?

**Comment by niladam** [comment]
@garyonyx - [this](https://novapackages.com/packages/owenmelbz/nova-radio-field) is a pretty solid alternative.

**Comment by voidgraphics** [comment]
No problems when using a File field for me. Works perfectly fine. Weird.

**Comment by wize-wiz** [comment]
@anakadote @niladam @garyonyx, as @voidgraphics already mentioned, I'm unable to reproduce with all flavours of Nova File types. It seems to work just fine when storing to local/public disk. Using latest v1.2 and Nova 2.3.

If there still is an issue, open a new one.
