### ISSUE TITLE
Doesn't update dynamically when depending on a BelongsTo field

### ISSUE THREAD

**Issue by pix2D** [epartment/nova-dependency-container#29]
When depending on a `BelongsTo` field on initial page load everything is calculated correctly, but then when the field changes nothing happens. I did test with a `Select` field and it worked fine with that.

I would guess that perhaps something is different with the `BelongsTo` Vue component compared to the other "standard" components?

**Comment by 949mac** [comment]
Check out #21 

> You should add HasDependencies trait to the nova Resource which uses NovaDependencyContainer

I solved this in my app by adding `use HasDependencies;` to the Nova Resource loading the `NovaDependencyContainer` field.

**Comment by axlot** [comment]
I can confirm this error, even with the use of HasDependencies; trait. The dependant fields are not displayed when the field you are depending on is a BelongsTo field.

**Comment by tudorradubarbu** [comment]
I have the same problem with BelongsTo fields

**Comment by mikaelpopowicz** [comment]
The component rely on `value` data attribute to check if dependency is satisfied. The BelongsToField component does not have a `value` but has a `selectedResourceId` data attribute.

**Comment by wize-wiz** [comment]
Fixes in #77
