### ISSUE TITLE
Doesn't work within NovaTab

### ISSUE THREAD

**Issue by szsori** [epartment/nova-dependency-container#3]
Nova Tabs allows grouping of fields into tabs:
https://github.com/arsenaltech/nova-tab

When I use a Dependency Container within a tab, it doesn't function when the checkbox is checked.  When I move it outside the tab it functions perfectly.

Sample:
```
new NovaTab(
  'Tab Name',
  [
     Boolean::make('Our Option', 'selectable_option')->hideFromIndex(),
     NovaDependencyContainer::make('Dependent settings', [
        Trix::make('Details', 'selectable_option_details'),
     ])->dependsOn('selectable_option', 1)->onlyOnForms(),
 ]
),
```

**Comment by unxsist** [comment]
Hi @szsori 

I've just pushed the 1.0.1 release that adds better scanning on field dependencies. You can now use tabs or any other container and the dependencies will work as expected.
