### ISSUE TITLE
Error working with hideWhenUpdating, hideWhenCreating, onlyOnForms, exceptOnForms

### ISSUE THREAD

**Issue by rjksn** [epartment/nova-dependency-container#33]
Hello,

I'm on Nova 1.1.8 and have been having issues trying to get this package to work with Nova's Default Showing/Hiding fields parameters. They don't seem to work when they're placed in `NovaDependencyContainer::make()` but they act as expected when placed outside of that. 

The simple code Illustration:

    // Will always display on forms
    NovaDependencyContainer::make([
        Text::make('NovaDependencyContainer Except on Forms', 'property')
            ->exceptOnForms(),
    ])->dependsOn('checkbox', true),

    // Will not display on forms
    Text::make('Except on Forms', 'property')
        ->exceptOnForms(),

Is this a feature that isn't supported and won't be supported? Or, is it a bug.

**Comment by rjksn** [comment]
[Nova Documentation on Showing / Hiding Fields](https://nova.laravel.com/docs/1.0/resources/fields.html#showing-hiding-fields)

**Comment by cristafortuno** [comment]
Running on the same issue as well.

**Comment by Ruitjes** [comment]
Any updates on this?

**Comment by Crov** [comment]
Hi there,

I ran into the same issue and finally figured it out. Not sure if anyone here managed to figure it out, but might be useful for someone else experiencing the problem.

You have to put the hide/show logic on the `NovaDependencyContainer` as this is the "filed" responsible for hiding/showing it's child fields.

```
// Will always display on forms
NovaDependencyContainer::make([
    Text::make('NovaDependencyContainer Except on Forms', 'property'),
])->dependsOn('checkbox', true)
->onlyOnForms(),
```
Hope that helps someone.

**Comment by wize-wiz** [comment]
like @Crov said.

If not resolved, open a new issue
