### ISSUE TITLE
Depends on unknown value?

### ISSUE THREAD

**Issue by peterbrinck** [epartment/nova-dependency-container#4]
Hi!

I have a field that's only required if a `BelongsTo` field is NOT EMPTY, how do I handle that?

By looking at the code, I can't figure out if it's already an option, but if not, it would be a nice feature.

It could be done the same way as the `where` clause, where you have an optional argument for the operator.

**Comment by unxsist** [comment]
Hi @peterbrinck, i've just tagged the 1.0.2 release introducing a `dependsOnNotEmpty` option in order to rely on non-empty fields.

If you have another suggestion to make this more dynamic, feel free to make a pull request!
