### ISSUE TITLE
Trying to get property of non-object, on boolean

### ISSUE THREAD

**Issue by tanthammar** [epartment/nova-dependency-container#41]
version 1.1.1
nova 1.3.0

Get an error on save/update when I try to depend on a boolean value that should be false.
"Trying to get property 'no_vat' of non-object"
```
Boolean::make('Vat Exempt', 'no_vat')
->help('Never invoice any vat for this company'),

NovaDependencyContainer::make([
Text::make( 'Vat ID', 'vat_id')->sortable()])
->dependsOn('no_vat', false),
```

**Comment by audetcameron** [comment]
try ->dependsOnNotEmpty('no_vat')

**Comment by wize-wiz** [comment]
@tanthammar unable to reproduce with latest v1.2, nova 2.3.1 and laravel 6. If problems remain, open a new issue
