### ISSUE TITLE
fields not shown when editing, you have to select a different value and then re select.

### ISSUE THREAD

**Issue by audetcameron** [epartment/nova-dependency-container#44]
After usin gthe DependencyContainer, if you go in to edit the resource, you have to deselect the dependsOn and re select it in order to see the values. 

Is there anyway to show the dependent containers on page load from an edit ?

***Update

This was an error on my end.  The column referenced needs to be an INT  and I had it as a VARCHAR.'

**Comment by ragingdave** [comment]
I don't think this is necessarily only you. I just ran into it while using this.
I have 3 containers depending on a select, so based on the selected value will show the right interpretation of the field. So for example:
   
    Select::make('Type')->options(['D' => 'Default', 'M' => 'OPT 1', 'L' => 'OPT 2']),

    NovaDependencyContainer::make([
        Select::make('Product Type', 'value')
            ->options(['*' => 'All'] + config('product_data.types'))
            ->displayUsingLabels(),
    ])->dependsOn('type', 'D'),

    NovaDependencyContainer::make([
        Text::make('Value'),
    ])->dependsOn('type', 'L'),

    NovaDependencyContainer::make([
        Manufacturer::make('Manufacturer', 'value') // List of manufacturers so a select
    ])->dependsOn('type', 'M'),


I am seeing that upon editing, the field is shown correctly based on the select, but is not pre-selecting the current value, for in this example type => M
