### ISSUE TITLE
If fields are named the same thing, always keeps the last value

### ISSUE THREAD

**Issue by jackabox** [epartment/nova-dependency-container#45]
Hi,

I've added three fields which are all called "Value" but have a different type of Text, Textarea or Boolean. This causes them always to have the last value, even if the nova dependency is not showing those fields. Is there anyway to implement three types for one column?

Code I'm using is below.

```
            NovaDependencyContainer::make([
                Boolean::make('Value')
                    ->hideFromIndex(),
            ])->dependsOn('type', 'boolean'),

            NovaDependencyContainer::make([
                Text::make('Value')
                    ->hideFromIndex(),
            ])->dependsOn('type', 'text'),

            NovaDependencyContainer::make([
                Textarea::make('Value')
                    ->hideFromIndex()
                    ->alwaysShow(),
            ])->dependsOn('type', 'textarea'),
```

**Comment by wize-wiz** [comment]
@jackabox I'm unable to reproduce this with the latest version v1.2, can you confirm? If not please open a new issue with example code.

**Comment by dividy** [comment]
@jackabox I have the same issue, did you find the reason ?

Also, problem #2, the fields appear on the edit view, but not on detail view, any idea ?

**Comment by ben182** [comment]
I have the same issue and did some more debugging on this. The problem is the boolean field. If you remove it everything works fine again. I will open a new issue.
