### ISSUE TITLE
Required triggers failed validation even if dependency isn't selected

### ISSUE THREAD

**Issue by audetcameron** [epartment/nova-dependency-container#47]
I have a Boolean::('mybool)  and a NovaDependencyContainer::  with dependsOnNotEmpty('mybool') and a text field inside.
The container seems to work fine in toggling the display of the text field, however if I add   ->rules('required') to the field inside the dependencyContainer it won't let me update the model unless the text field is filled out even if I have not triggered the boolean to show the text field.   Is there a way to only make the field required if the field is visible in the container?

**Comment by tufankilicaslan** [comment]
this pull request https://github.com/epartment/nova-dependency-container/pull/37 may solve the problem.

**Comment by alex-osborn** [comment]
Yes, use required_if matching the same rules as the container.

```
            NovaDependencyContainer::make([`
                Text::make('Meter Reading')
                    ->rules('required_if:sensor_type_id,1'),
            ])
                ->dependsOn('sensor_type_id', '1'),
```

**Comment by wize-wiz** [comment]
If not solved, open a new issue
