### ISSUE TITLE
The demo doesn't work for me. (with workaround)

### ISSUE THREAD

**Issue by netbuilding** [epartment/nova-dependency-container#48]
I don't know why, but the demo doesn't work for me. 

laravel/framework: v5.7.26
laravel/nova: v1.3.2
epartment/nova-dependency-container: 1.1.1

I used the demo code in resource, the "first_name" text field doesn't appear when "name_format" equals 0. After investigation, I found the value in "name_format" is string. The source code of this package use !== to check it's value and change dependenciesSatisfied to true if they are equal. 

I converted the value in "depensOn" property to string that works. 

Here is workaround:

```
class Page extends Resource
{
    use HasDependencies;

    public function fields(Request $request)
    {
        return [

            Select::make('Name format', 'name_format')->options([
                0 => 'First Name',
                1 => 'First Name / Last Name',
                2 => 'Full Name'
            ])->displayUsingLabels(),

            NovaDependencyContainer::make([
                Text::make('First Name', 'first_name')
            ])->dependsOn('name_format', "0"),  // <---- change it to string

        ];
    }
}
```

Please check the source code or update the demo accordingly. Thanks.

**Comment by LevFlavien** [comment]
I think it happens since Nova 1.3.2. Using an integer worked before.

**Comment by colemvn** [comment]
I'd just like to add, that on Nova 2.0
This fix, makes the DEMO work.
(Thank you @netbuilding !)
