### ISSUE TITLE
Hidden fields in edit view since Nova 1.3.2

### ISSUE THREAD

**Issue by LevFlavien** [epartment/nova-dependency-container#49]
laravel/framework: v5.7.26
laravel/nova: v1.3.2
epartment/nova-dependency-container: 1.1.1

When editing a resource, the dependent fields are hidden by default and require the trigger field to emit a change in order to display again.
This happens since Nova 1.3.2.

**Comment by GrzegorzJaworski** [comment]
I had the same problem. When I take Int values to quotes it started working.
