### ISSUE TITLE
Boolean values always are false in dependency container

### ISSUE THREAD

**Issue by ArmeniaH** [epartment/nova-dependency-container#50]
laravel/framework: v5.7.26
laravel/nova: v1.3.2
epartment/nova-dependency-container: 1.1.1

I have 2 Boolean fields in DependecyContainer
```
Text::make('Domain'),
NovaDependencyContainer::make([
    Boolean::make('Redirect to www')->rules('required'),
    Boolean::make('Force HTTPS'),
])->dependsOnNotEmpty('domain'),
```

When I check the checkboxes, The request has the values as true, but the response always is false for these boolean fields.

If I remove the container and just use Boolean fields, everything works as expected.

**Comment by yaroslavshyshkin** [comment]
Same trouble:

- laravel/nova: v1.3.2
- epartment/nova-dependency-container: 1.1.1

Though with only one boolean field:

`NovaDependencyContainer::make([
                Boolean::make('Subscribed', 'no_bulk')

            ])->dependsOnNotEmpty('do_not_contact'),`

**Comment by FhatFreak** [comment]
I'm having the same issue as @yaroslavshyshkin and @ArmeniaH 
- laravel/nova v1.3.2
- epartment/nova-dependency-container: 1.1.1

NovaDependencyContainer::make([
    Boolean::make('Has Billable Shipping'),
])->dependsOn('is_material', true),

**Comment by ArmeniaH** [comment]
@unxsist Any chance we will get update any time soon?

**Comment by wize-wiz** [comment]
@ArmeniaH @yaroslavshyshkin @FhatFreak  I'm unable to reproduce the problem with given examples, it seems to work just fine, tested with latest v1.2, Laravel 5.8|6.0 and Nova 2.3, can you confirm?
