### ISSUE TITLE
Not working nova-repeatable-fields

### ISSUE THREAD

**Issue by rmmaitrey** [epartment/nova-dependency-container#53]
This package looks good but I am not able to use it with the package.

[nova-repeatable-fields](https://github.com/fourstacks/nova-repeatable-fields)

Can anyone help ?

**Comment by wize-wiz** [comment]
@rmmaitrey could you elaborate a bit more what isn't working and add some example code?

**Comment by wize-wiz** [comment]
The package [nova-repeatable-fields](https://github.com/fourstacks/nova-repeatable-fields) by fourstacks is not actively developed anymore. The author recommends using [flexible-content](https://github.com/whitecube/nova-flexible-content/issues) by whitecube  instead.
