### ISSUE TITLE
Causes failure for Maatwebsite/Laravel-Nova-Excel package

### ISSUE THREAD

**Issue by nysso** [epartment/nova-dependency-container#54]
After installing **epartment/nova-dependency-container** another package got affected, the **Maatwebsite/Laravel-Nova-Excel**
and got the **wrong data passed to foreach()** error when exporting excel data using Maatwebsite/Laravel-Nova-Excel

**Comment by wize-wiz** [comment]
@nysso I'm having problems too with the this package but I'm unable to reproduce the error. Could you give me a code example where this error occurs?

**Comment by wize-wiz** [comment]
I believe this has been fixed in 1.2.2. If there are still problems, then please open a new issue.
