### ISSUE TITLE
Nova Nested Form

### ISSUE THREAD

**Issue by YuCoLabKenny** [epartment/nova-dependency-container#57]
@unxsist @michielkempen  Unfortunately, it's not working with the package [Nova Nested Form](https://github.com/yassipad/laravel-nova-nested-form).

I use that dependency-container to show certain attributes when something is selected in the form. But when I use NestedForms and I select something in the select-box, nothing happens.

Is there a workaround? Would be great to use both in the same Nova model.

**Comment by wijourdil** [comment]
I have the same issue with NovaTabs, it doesn't work if a DependenciesContainer is in a NovaTab.

**Comment by wize-wiz** [comment]
@YuCoLabKenny could you supply a working example?

**Comment by hadinajem** [comment]
@YuCoLabKenny did you find a way to make it work?

**Comment by socramjunio2** [comment]
Eu consegui resolver e utilizar o dependency dentro do Nested Form, se alguém quiser é só falar que mando um pull ;)
