### ISSUE TITLE
dependsOnEmpty relation

### ISSUE THREAD

**Issue by tumispro** [epartment/nova-dependency-container#58]
A dependsOnEmpty relation (opposite of dependsOnNotEmpty) would be really useful. A field is then required only when another one is not filled out. In my case I want to allow users to either fill out a URL field, or select a related resource to link to.

(if this is already possible currently I'd like to know how! Using dependsOn('field', null) doesn't seem to work, at least not for a select field)

**Comment by nsrosenqvist** [comment]
This would be great and probably a quite simple feature to add?

**Comment by nsrosenqvist** [comment]
@unxsist after browsing through the code it seems like only 3 changes are necessary (unless I've missed something):

Insert at **FormField.vue** line 76
```js
					if(dependency.hasOwnProperty('empty') && this.dependencyValues[dependency.field]) {
						this.dependenciesSatisfied = false;
						return;
					}
```

Insert at **NovaDependencyContainer.php** line 64:
```php
    /**
     *
     *
     * @param $field
     * @return NovaDependencyContainer
     */
    public function dependsOnEmpty($field)
    {
        return $this->withMeta([
            'dependencies' => array_merge($this->meta['dependencies'], [['field' => $field, 'empty' => true]])
        ]);
    }
```

Insert at **NovaDependencyContainer.php** line 77 (now 90):
```php
            if(array_key_exists('empty', $dependency) && empty($resource->{$dependency['field']})) {
                $this->meta['dependencies'][$index]['satisfied'] = true;
            }
```

**Comment by wize-wiz** [comment]
@nsrosenqvist so where the PR? :)

**Comment by nsrosenqvist** [comment]
@wize-wiz I would have created one if I had time, due to constraints I just worked around the issue. If it becomes an issue foe me again I'll probably clone and create a PR. If someone else is willing to take the time then there should be enough information here to do so.

**Comment by wize-wiz** [comment]
Added in https://github.com/epartment/nova-dependency-container/commit/1fb8b97694b915e3c344f46df99b3f42b1c6163c
