### ISSUE TITLE
Dependable MorphTo will not work correctly

### ISSUE THREAD

**Issue by preliot** [epartment/nova-dependency-container#62]
When using a MorphTo Field in a Nova Dependency Container, it wil fail. You can select a Client or Department (see example), but then i can't select the specific Client or Department, because of an error.

```php
 $fields[] = NovaDependencyContainer::make([
                     Fields\MorphTo::make('org_level')
                ->types([\App\Nova\OrgLevel\Client::class, \App\Nova\OrgLevel\Department:class]);
                ])->dependsOn('some_other_field', 'some_value');

\\Will result in this error
[2019-06-17 10:39:02] local.ERROR: Call to a member function buildMorphableQuery() on null {"userId":1,"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function buildMorphableQuery() on null at <path-to-my-project>
```

This issue can be traced to:

```php
Laravel\Nova\Http\Controllers\MorphableController.php > index method

$field = $request->newResource()
                        ->availableFields($request)
                        ->firstWhere('attribute', $request->field);

```
$field will be null and therefore the method will fail with the exception.

**Comment by artisaninweb** [comment]
Got the same issue.

**Comment by wize-wiz** [comment]
@preliot @artisaninweb could one of you give me a short working example with models/resources on how you build the relationships?

**Comment by preliot** [comment]
Update: just updated to Nova 2.4.0 and not seeing it anymore. Not sure if the update fixed it **or** something i've done earlier. Saw a comment in my code, could be a hint:

//bugfix: field uses a morphTo, which adds **required rule** to org_level_type.

**Comment by wize-wiz** [comment]
@preliot That's good to hear, you could close this issue if the problem is fixed and open a new issue if something pops up again somewhere else.

**Comment by mira-thakkar** [comment]
@preliot i am facing this issue in nova 3.14 and package version 1.12.
Can you help me know how you fixed it?

**Comment by preliot** [comment]
> @preliot i am facing this issue in nova 3.14 and package version 1.12.
> Can you help me know how you fixed it?

Could you open a new issue and give some more details?

**Comment by mira-thakkar** [comment]
@preliot Sure. [Here](https://github.com/epartment/nova-dependency-container/issues/141) it is
