### ISSUE TITLE
Redirects everything to http://127.0.0.1:8000/nova-api/scripts/nova-dependency-container

### ISSUE THREAD

**Issue by banstola** [epartment/nova-dependency-container#67]
If a route is not found then instead of 404, the application redirects to 
/nova-api/scripts/nova-dependency-container when logged in

I have my route as below

```
Route::get('/myroute/{dynamic-uri}','MyControllerController@mymethod');
```
Then if i visit 
/myroute --- it redirects to /nova-api/scripts/nova-dependency-container with the js file

**Comment by wize-wiz** [comment]
@banstola I don't see how this is related to this package. This package doesn't add any routes, so I highly suspect this problem lies somewhere in your routing configuration.
