### ISSUE TITLE
This project is not abandoned 🤗

### ISSUE THREAD

**Issue by wize-wiz** [epartment/nova-dependency-container#76]
I've contacted the author of this package for his permission to maintain and continue the development of this package. In the next days I will review all PR's and try to handle/sort/answer most of the issues.

Anybody who wants to help, just leave a note.

**Comment by jnbn** [comment]
Congratulations @wize-wiz . We'll be trying our best w/ @d35k

**Comment by jnbn** [comment]
I'd suggest releasing 1.2.0 for the Laravel 6 support as soon as possible.

**Comment by wize-wiz** [comment]
Yea I'm on it, I'm testing locally now to see if everything works as the README describes on how it should work. All other problem like problems with other packages or bugs are going to be fixed in 1.2.x versions. Milestone was more like a quick idea, 1.3.x will be all fixes and sorted issues. I'll change that in a bit.
