### ISSUE TITLE
[BUG] Belongs not working properly 

### ISSUE THREAD

**Issue by skoyah** [epartment/nova-dependency-container#80]
Having a `BelongsToField` inside the container is not working as expected. Although it saves the value in the database, every time we refresh the page, the field is empty.

At first, I thought it was only a rendering issue, but if I make the field as required, it still asks for the required field.

<img width="658" alt="Screenshot 2019-10-02 at 20 54 41" src="https://user-images.githubusercontent.com/36083448/66073575-94a0ea80-e557-11e9-9a86-ee72dce33e03.png">
<img width="952" alt="Screenshot 2019-10-02 at 21 00 32" src="https://user-images.githubusercontent.com/36083448/66073627-bac68a80-e557-11e9-98a8-7d825f187db8.png">

**Comment by wize-wiz** [comment]
@skoyah Thanks for input, I'll take a quick look.

**Comment by skoyah** [comment]
Thank you @wize-wiz ! Is quite a roadblock for our current project. :) 

Also made a quick inspection with Vue Dev tools and its confirmed that the value of the field is null inside the container.

**Comment by wize-wiz** [comment]
@skoyah Yea I found the problem, there are some other small bugs that will be released soon. I'll try to make a clean fix and push this one to 1.2.3.

**Comment by skoyah** [comment]
Thank you! Could you point me out the problem so I can make a quick fix while the new version is not out?

**Comment by wize-wiz** [comment]
Pushed in 1.2.3, should be working now, please verify and close if so :)

**Comment by skoyah** [comment]
@wize-wiz I can confirm that this issue was resolves with latest release. Thank you!
