### ISSUE TITLE
undefined index error after upgrading to nova 2.5.0

### ISSUE THREAD

**Issue by nemrutco** [epartment/nova-dependency-container#86]
i am not sure why but i think there is a compatibility  issue with nova 2.5.0, everything is fine until nova 2.4.0 version.

**Comment by snk-lab** [comment]
Exactly the same in my environment

**Comment by Tarpsvo** [comment]
It's definitely in the right place.

To fix this temporarily in your project, you can just add this to each `NovaDependencyContainer`:

```php
->required(function () {
  return true;
})
```

**Comment by wize-wiz** [comment]
@nemrutco @Tarpsvo @snk-lab Yea they added `requiredCallback` to `Fields.php`. A simple return false in the `NovaDependencyContainer` class constructor would fix it.

```php
public function __construct($fields, $attribute = null, $resolveCallback = null)
{
    parent::__construct('', $attribute, $resolveCallback);

    $this->withMeta(['fields' => $fields]);
    $this->withMeta(['dependencies' => []]);

    $this->requiredCallback = function() { return false; };
}
```

But I'm not sure if this is just a workaround or an actual fix. They seem to be mixing a lot now in `Fields.php`.

**Comment by Tarpsvo** [comment]
I don't really like the solution of adding a useless `requiredCallback` (even though it is a fix) and I'm hoping they merge my PR with the `!empty($this->attribute)` check.

Giving the NovaDependencyContainer an actual attribute should also be a fix, though I haven't tested it and the attribute itself would also be equally useless.

**Comment by nemrutco** [comment]
> I don't really like the solution of adding a useless `requiredCallback` (even though it is a fix) and I'm hoping they merge my PR with the `!empty($this->attribute)` check.
> 
> Giving the NovaDependencyContainer an actual attribute should also be a fix, though I haven't tested it and the attribute itself would also be equally useless.

>Follow updates at laravel/nova#684.

your link gets 404, that's why i asked are you sure you posted in right place.

**Comment by wize-wiz** [comment]
@nemrutco Yea `laravel/nova` isn't public as far as I know.

@Tarpsvo A PR doesn't help much if nova expects a key to be present in an array, where some PR for this package obviously didn't wrote anything compatible to novas behaviour prior to 2.5.0. 

The default behaviour should apparently always be. 

```php
return [$this->attribute => [..]];
```
Although it would nice to check the index first, I think they made this choice to escalate deliberately.

Should be fixed in [1.2.7](https://github.com/epartment/nova-dependency-container/releases/tag/1.2.7), please verify and if so close this issue.

**Comment by snk-lab** [comment]
The problem could be avoided by including the following.
`->required(function () {
  return false;
})`

**Comment by snk-lab** [comment]
@wize-wiz 
> @snk-lab `composer update epartment/nova-dependency-container` should accomplish the same thing without requiring anything in your code.

Thank you very much. Updated to remove unnecessary modifications.

**Comment by nemrutco** [comment]
> @snk-lab `composer update epartment/nova-dependency-container` should accomplish the same thing without requiring anything in your code.
Problem solved. Thanks

**Comment by wize-wiz** [comment]
Please close this issue if resolved.
