### ISSUE TITLE
Currency field not compatible with resolve logic

### ISSUE THREAD

**Issue by ragingdave** [epartment/nova-dependency-container#89]
The Currency field in nova has by default a displayUsing which will autoformat an empty value to something like `USD 0.00` which then can break storage. It looks like this has to be a part of the resolve switch to handle currency via a direct resolve call rather than delegating.

**Comment by wize-wiz** [comment]
@ragingdave I'm unable to reproduce. Default currency is not applied when value is `null`, which nova translates to `--`. Could you supply an example of your implementation?

**Comment by ragingdave** [comment]
Hmm... Well it's a pretty simple setup:

            NovaDependencyContainer::make([
                Currency::make('price')
                    ->hideFromIndex(),
            ])->dependsOn('attr', 'T'),

It would seem that I was incorrect in the assumption about empty being formatted. It's actually when the underlying value of the currency field is `0.00`, the field is treated as empty, and is formatted to be `USD 0.00`  instead of just `0.00`. This used to be a bug in nova but was fixed and can confirm that when this field isn't wrapped by this dependency container it works as expected. 

So to be clear the case that is failing is when the underlying value of the field is `0.00`. The UI on the edit page acts as though there is no value and the field is left blank. If this container is removed from wrapping the Currency field, the value on the edit page is shown appropriately.

The related nova-issue is https://github.com/laravel/nova-issues/issues/514.

**Comment by wize-wiz** [comment]
@ragingdave Even it if closed automatically, can you confirm 1.2.8 solves it? If not, just open a new issue.

**Comment by ragingdave** [comment]
Will look into testing it tomorrow. Thanks for the quick work!
