### ISSUE TITLE
Add Ability for dependsOnNot

### ISSUE THREAD

**Issue by ragingdave** [epartment/nova-dependency-container#94]
This would be very helpful to be able to display either fallback detail page information/heading in case of an empty panel due to all other fields being hidden by a dependsOn clause.

**Comment by wize-wiz** [comment]
@ragingdave in other words, `dependsOn` equals `==`, and `dependsOnNot` equals `!=`?

**Comment by ragingdave** [comment]
pretty much

**Comment by wize-wiz** [comment]
@ragingdave Do you want to have the honor of a PR? :)

**Comment by ragingdave** [comment]
I can certainly give it a shot! :)
